theme: jekyll-theme-cayman

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-3W40Q0G6P2"
    anonymize_ip         : # true, false (default)
